### PR TITLE
Restart cluster tasks on connection lost

### LINKED ISSUE #813: Retries in cluster requests
When cluster request to object storage is executed, some node can be failed (swarm downscale, some kubernetes actions, etc.)

Now executed request is also failed.

Need to reuse other alive nodes to continue request execution.

### PR DESCRIPTION
**Pull request by ianton-ru**
### Changelog category (leave one):
- Experimental Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Restart loading objects on other nodes when one node down in cluster request.

### Documentation entry for user-facing changes
When swarm node takes some tasks to execute and goes down, if no data from this node were processed, task can be returned back to common queue to be executed on other node, if any still alive.

Did not managed to make test, tested with adding sleep in code to be able to kill some replica in that time slot.

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [x]  All with ASAN
- [x]  All with TSAN
- [x]  All with MSAN
- [x]  All with UBSAN
- [ ]  All with Coverage
- [ ]  All with Aarch64
- [x]  All Regression
- [ ]  Disable CI Cache

### CODE REVIEW

File: src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp [hunk 1]
```diff
@@ -179,4 +199,28 @@ std::optional<String> StorageObjectStorageStableTaskDistributor::getAnyUnprocess
     return std::nullopt;
 }
 
+void StorageObjectStorageStableTaskDistributor::rerunTasksForReplica(size_t number_of_current_replica)
```
Comment (arthurpassos) [inline src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp]: If I understand correctly, this method re-schedules the tasks FROM a given replica to another one. Is that correct?

If that's so, I would name it differently:

`rescheduleTasksFromReplica`

File: src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp [hunk 2]
```diff
@@ -24,16 +33,27 @@ std::optional<String> StorageObjectStorageStableTaskDistributor::getNextTask(siz
...
     );
 
-    // 1. Check pre-queued files first
-    if (auto file = getPreQueuedFile(number_of_current_replica))
-        return file;
+    auto processed_file_list_ptr = processed_files.find(number_of_current_replica);
+    if (processed_file_list_ptr == processed_files.end())
+        throw Exception(
+            ErrorCodes::LOGICAL_ERROR,
+            "Replica number {} was marked as lost, can't set satk for it anymore",
```
Comment (arthurpassos) [inline src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp]: typo

File: src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.h [hunk 3]
```diff
@@ -34,6 +39,7 @@ class StorageObjectStorageStableTaskDistributor
     std::unordered_set<String> unprocessed_files;
 
     std::vector<std::string> ids_of_nodes;
+    std::unordered_map<size_t, std::list<String>> processed_files;
```
Comment (arthurpassos) [inline src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.h]: replica_to_files_to_be_processed_map or something like this.

imo

1. It needs to mention it is a mapping from replica to list of files
2. it can't be "processed" as it is in the past tense because the files haven't been processed yet as far as I understand

File: src/QueryPipeline/RemoteQueryExecutorReadContext.cpp [hunk 4]
```diff
@@ -54,18 +58,29 @@ void RemoteQueryExecutorReadContext::Task::run(AsyncCallback async_callback, Sus
...
+                suspend_callback();
+            }
+            read_context.packet = read_context.executor.getConnections().receivePacketUnlocked(async_callback);
+            read_context.has_read_packet_part = PacketPart::Body;
             suspend_callback();
         }
-        read_context.packet = read_context.executor.getConnections().receivePacketUnlocked(async_callback);
-        read_context.has_read_packet_part = PacketPart::Body;
+    }
+    catch (const Exception &)
```
Comment (arthurpassos) [inline src/QueryPipeline/RemoteQueryExecutorReadContext.cpp:78]: Shouldn't you catch only network related exceptions? Or maybe the question is: is there an non-connection-loss related exceptionthat could be thrown?

**Review by arthurpassos — COMMENTED** [review]
First round

File: src/QueryPipeline/RemoteQueryExecutorReadContext.cpp (hunk 4 above)
Comment (ianton-ru) [reply src/QueryPipeline/RemoteQueryExecutorReadContext.cpp:78]: Only network exceptions - may be.
Others - not sure, It replica sent an exception because data corrupted (it may be unpredictable error), other replica with the same data gets the same error. May be possible to reschedule task with some specific exceptions, but need to know this specific cases. I don't know right now. If we found something, we can add this later.

File: src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp (hunk 1 above)
Comment (ianton-ru) [reply src/Storages/ObjectStorage/StorageObjectStorageStableTaskDistributor.cpp]: Yes, it adds tasks from replica to unprocessed list to allow other replicas take them.

File: src/QueryPipeline/RemoteQueryExecutor.h [hunk 5]
```diff
@@ -8,6 +8,8 @@
 #include <Interpreters/StorageID.h>
 #include <sys/types.h>
 
+#include <list>
```
Comment (arthurpassos) [inline src/QueryPipeline/RemoteQueryExecutor.h]: Do you need this header here?

**Review by arthurpassos — COMMENTED** [review]
A few questions that come to mind right now:

1. Does a replica ever gets reconnected after being marked as lost?
2. As far as I understand, once a replica is assigned a file, it'll process that file and return the result before picking the next file. Therefore, `StorageObjectStorageStableTaskDistributor::processed_files` should be updated, shouldn't it?

File: src/QueryPipeline/RemoteQueryExecutor.h (hunk 5 above)
Comment (ianton-ru) [reply src/QueryPipeline/RemoteQueryExecutor.h]: Forget to remove, thanks

**Comment by ianton-ru** [comment]
> 1. Does a replica ever gets reconnected after being marked as lost?
Not in this query. The problem exist only when replica already took some files to process it and goes down before processed all data. We can reschedule task only when initiator did not get any parts of data, because this parts are merged into response, and now impossible to "unmerge" them back to process all file, and we have no information to process only unprocessed part of file on other node.
> 2. As far as I understand, once a replica is assigned a file, it'll process that file and return the result before picking the next file. Therefore, `StorageObjectStorageStableTaskDistributor::processed_files` should be updated, shouldn't it?
Each replica takes several files (4 by default) to process in parallel. And in partial responses no information from which file is this response. So - impossible to separate data of completed files from data of non-completed, and when initiator gets something impossible to reschedule tasks.

**Comment by ianton-ru** [comment]
Can be rebased on antalya-25.3 branch only after merge of  #797, feature depends on rendezvous hashing (uses same class).

**Comment by ianton-ru** [comment]
Fixed after review and rebased

**Comment by ianton-ru** [comment]
Rebased on antalya-25.6.5 branch

**Comment by Enmk** [comment]
closing to reopen later to retrigger CI/CD
