### PR TITLE
Antalya 25.8 Backport of #93866 - Google cloud storage support for data lakes catalogs

### LINKED ISSUE #1199: Antalya does not see tables on iceberg using nessie catalog + GCS
**Describe the bug**
When using the [nessie](https://projectnessie.org/) REST catalog for iceberg, and using `SHOW TABLES`, antalya does not see any tables despite successfully traversing the catalog  

**To Reproduce**

In brief this is the reproduction steps

1. Spin up nessie and clickhouse
2. Create and write to an iceberg table
3. Create an iceberg database
4. `USE` said iceberg database
5. `SHOW TABLES` -> see no tables show up

**For Detailed steps**: see the attached zip file `README.md` for complete steps on reproduction. I think the issue has something to do with the parsing of the iceberg REST catalog response. 

**Expected behavior**
The database shows the tables existing in the catalog

**Key information**
Provide relevant runtime details. 
 - Project Antalya Build Version: 25.8.9.20496.altinityantalya
 - Cloud provider: GCP
 - Kubernetes provider: None, used docker compose
 - Object storage: GCS
 - Iceberg catalog: Nessie

**Additional context**
See zip file for an easy repro step

[iceberg-clickhouse-repro.zip](https://github.com/user-attachments/files/24042685/iceberg-clickhouse-repro.zip)

### PR DESCRIPTION
**Pull request by mkmkme**
Google cloud storage support for data lakes catalogs (fixes #1199)

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Google cloud storage support for data lakes (https://github.com/ClickHouse/ClickHouse/pull/93866 by @scanhex12)

#### Exclude tests:
- [ ]  Fast test
- [ ]  Integration Tests
- [ ]  Stateless tests
- [ ]  Stateful tests
- [ ]  Performance tests
- [x]  All with ASAN
- [x]  All with TSAN
- [x]  All with MSAN
- [x]  All with UBSAN
- [x]  All with Coverage
- [ ]  All with Aarch64
- [ ]  All Regression
- [ ]  Disable CI Cache

#### Regression jobs to run:
- [ ]  Fast suites (mostly <1h)
- [ ]  Aggregate Functions (2h)
- [ ]  Alter (1.5h)
- [ ]  Benchmark (30m)
- [ ]  ClickHouse Keeper (1h)
- [ ]  Iceberg (2h)
- [ ]  LDAP (1h)
- [ ]  Parquet (1.5h)
- [ ]  RBAC (1.5h)
- [ ]  SSL Server (1h)
- [ ]  S3 (2h)
- [ ]  Tiered Storage (2h)

### CODE REVIEW

File: src/Databases/DataLake/ICatalog.cpp [hunk 1]
```diff
@@ -49,9 +57,14 @@ StorageType parseStorageTypeFromString(const std::string & type)
     }
     if (capitalize_first_letter(storage_type_str) == "File")
         storage_type_str = "Local";
-
-    if (capitalize_first_letter(storage_type_str) == "S3a")
+    else if (capitalize_first_letter(storage_type_str) == "S3a" || storage_type_str == "oss" || storage_type_str == "gs")
+    {
+        fiu_do_on(DB::FailPoints::database_iceberg_gcs,
```
Comment (mkmkme) [inline src/Databases/DataLake/ICatalog.cpp:62]: This particular bit I don't really like. It's there only for the sake of the integration test. But I've left it intact to be more aligned with the upstream.

**Review by arthurpassos — APPROVED** [review]
LGTM

File: src/Databases/DataLake/ICatalog.cpp (hunk 1 above)
Comment (arthurpassos) [reply src/Databases/DataLake/ICatalog.cpp:62]: Better & easier to keep it consistent :+1:

**Comment by CarlosFelipeOR** [comment]
### QA Verification

This PR was **verified manually** using a real Iceberg setup backed by **Google Cloud Storage (GCS)** and a local **Nessie REST catalog**.

The verification **followed the reproduction steps documented in issue #1199**.

---

### Test environment
- ClickHouse **binary** (not Docker)
- **Nessie REST catalog** running locally
- Iceberg tables stored on **GCS**
- Tested with:
  - **Private GCS bucket (with credentials)**
  - **Public GCS bucket (no credentials)**

---

### Validation steps

Before running the ClickHouse queries:

- GCS access was configured locally using a **GCP Service Account**  (`GOOGLE_APPLICATION_CREDENTIALS` pointing to the QA service account JSON)
- The **Nessie REST catalog** was started via Docker and exposed at  `http://localhost:19120/iceberg`, with the warehouse explicitly configured as:

```

gs://altinity-qa-test/carlos_test/

````

This ensures the **`gs://` storage path** is exercised.
- The Iceberg table was populated by running the **`write_to_iceberg.py` script** provided in the issue, which creates the namespace and table via Nessie and writes both metadata and data files to GCS

---

### ClickHouse validation

```sql
CREATE DATABASE demo_local
ENGINE = DataLakeCatalog('http://localhost:19120/iceberg')
SETTINGS
  catalog_type = 'rest',
  storage_endpoint = 'https://storage.googleapis.com',
  warehouse = 'warehouse';
````

```sql
USE demo_local;
```

```sql
SHOW TABLES;
```

Result:

```
┌─name───────────────────────┐
│ local_dataset.taxi_dataset │
└────────────────────────────┘
```

```sql
SELECT count() FROM `local_dataset.taxi_dataset`;
```

Result:

```
┌─count()─┐
│ 3475226 │
└─────────┘
```

---

### Result

* Iceberg tables created via **Nessie** are correctly discovered by ClickHouse
* Metadata and data stored on **GCS** are read successfully
* The **`gs://` warehouse path** is handled correctly
* Data is accessible and queryable
* Verified with both **private and public GCS buckets**

✅ Confirmed working when using **Iceberg tables stored on GCS and accessed via the Nessie REST catalog**.
